name: Pikafish

on:
  push:
    branches:
      - linux_test

jobs:
  Pikafish:
    name: ${{ matrix.config.name }}${{ matrix.arch }}
    runs-on: ${{ matrix.config.os }}
    env:
      ARCH: x86-64${{ matrix.arch }}
      COMPCXX: clang++
      COMP: clang
      EXE: pikafish${{ matrix.arch }}${{ matrix.config.ext }}
      SDE: ${{ matrix.config.sde }}
    strategy:
      matrix:
        config:
          - name: Linux
            os: ubuntu-20.04 
            shell: bash
            sde: /home/runner/work/Pikafish-HCE/Pikafish-HCE/.output/sde-temp-files/sde-external-9.27.0-2023-09-13-lin/sde -future --
        arch: ["-bmi2"]
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM and Clang
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install clang llvm

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang make git expect

      - name: Download SDE package
        if: runner.os == 'Linux' || runner.os == 'Windows'
        uses: petarpetrovt/setup-sde@91a1a03434384e064706634125a15f7446d2aafb  # @v2.3
        with:
          environmentVariableName: SDE_DIR
          sdeVersion: 9.27.0

      - name: Compile ${{ matrix.arch }} build
        run: |
          make -j profile-build EXE=$EXE WINE_PATH="$SDE"
          make strip EXE=$EXE
          cp $EXE ../

      - name: Download wiki
        run: |
          git clone https://github.com/official-pikafish/Pikafish.wiki.git ../Wiki
          cd ../Wiki
          rm -rf .git

      # Artifacts automatically get zipped.
      # To avoid double-zipping, we use the unzipped directory
      - uses: actions/upload-artifact@v4
        with:	
          name: Pikafish-${{ matrix.config.name }}${{ matrix.arch }}
          path: |
            ${{ env.EXE }}
            Wiki
            AUTHORS
            CONTRIBUTING.md
            Copying.txt
            README.md
            Top CPU Contributors.txt
